- app/src/main/java/org/teamone/client/appointments/EditAppt.java
- app/src/main/java/org/teamone/client/appointments/HSPSelectPatient.java
- app/src/main/java/org/teamone/client/appointments/HSPSelectPatientEdit.java
- app/src/main/java/org/teamone/client/appointments/PatientSchedAppt.java
- app/src/main/java/org/teamone/client/appointments/ViewAppt.java
- app/src/main/webapp/WEB-INF/jsp/appointment/EditAppt.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/HSPSelectPatient.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/HSPSelectPatientEdit.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/PatientSchedAppt.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/ViewAppt.jsp
- core/src/main/java/org/teamone/core/appointments/Appointment.java
- core/src/main/java/org/teamone/core/users/PersonUtils.java
Everything we have done so far for appointments works properly and is ready to be merged into master
> Schedule appointments new frontend

- app/src/main/java/org/teamone/client/auth/LoginController.java
- app/src/main/java/org/teamone/client/auth/UserController.java
- app/src/main/webapp/WEB-INF/jsp/auth/login.jsp
- core/src/main/java/org/teamone/core/SQL/LoginSQL.java
- core/src/test/java/org/teamone/core/LoginTest.java
- core/src/test/java/org/teamone/core/PatientUpdateInfoTest.java
can @rang1 test this and then confirm the merge?
> Login integration

- core/src/main/java/org/teamone/core/users/Patient.java
- core/src/main/java/org/teamone/core/users/PatientInformation.java
I don't think this broke an SQL code...All refs were fixed.
> updated patient class with PatientInformation class

- core/src/main/java/org/teamone/core/users/MedicalHistory.java
- core/src/main/java/org/teamone/core/users/Patient.java
- core/src/test/java/org/teamone/core/baseclasstests/PatientTest.java
added a core class to organize HealthConditions.
also added test.
> added HealthConditions base class

- .travis.yml
- core/src/main/java/org/teamone/core/SQL/AppointmentViewEdit.java
- core/src/main/java/org/teamone/core/SQL/HSPRegistration.java
- core/src/main/java/org/teamone/core/SQL/LoginSQL.java
- core/src/main/java/org/teamone/core/SQL/PatientHealthCondtions.java
- core/src/main/java/org/teamone/core/SQL/PatientUpdateInfo.java
- core/src/main/java/org/teamone/core/SQL/pass.java
- core/src/main/java/org/teamone/core/users/PersonUtils.java
- core/src/test/java/org/teamone/core/AppointmentTester.java
- core/src/test/java/org/teamone/core/HealthConditionUpdateTest.java
- core/src/test/java/org/teamone/core/LoginTest.java
- core/src/test/java/org/teamone/core/PatientUpdateInfoTest.java
- core/src/test/java/org/teamone/core/StaffListTest.java
- core/src/test/java/org/teamone/core/baseclasstests/TestStrings.java
- cse360.sql
updated multiple println statements in backend.
added one password file, will be easier for 20 backend codes
> Travis sql

- core/src/main/java/org/teamone/core/SQL/HspSQL.java
- core/src/test/java/org/teamone/core/RegisterTest.java
- core/src/test/java/org/teamone/core/zAdmin.java
- cse360.sql
> Update rng backend

- app/src/main/java/org/teamone/client/patient/PersonalController.java
- app/src/main/webapp/WEB-INF/jsp/patient/patient-PersonalInformation.jsp
New branch, should be the same as previous, but with updated master
> Patient Personal Information Update -- Patients side

- app/src/main/java/org/teamone/client/healthconditions/HealthConditionsController.java
- app/src/main/java/org/teamone/client/patient/PersonalController.java
- app/src/main/webapp/WEB-INF/jsp/patient/patient-PersonalInformation.jsp
Patients can update their health conditions
> healthConditions-frontend

- app/src/main/java/org/teamone/client/medicalhistory/MedicalHistoryController.java
- app/src/main/webapp/WEB-INF/jsp/medical-history/editmedicalhistory.jsp
- core/src/main/java/org/teamone/core/SQL/PatientSQL.java
- core/src/test/java/org/teamone/core/HealthConditionTest.java
Patient can update thier medical conditions
> Medical Conditions

- app/src/main/webapp/WEB-INF/jsp/health-conditions/edithealthconditions.jsp
- app/src/main/webapp/WEB-INF/jsp/medical-history/editmedicalhistory.jsp
- app/src/main/webapp/WEB-INF/jsp/patient/patient-PersonalInformation.jsp
- app/src/main/webapp/WEB-INF/jsp/registration/hsp-healthConditions.jsp
- app/src/main/webapp/WEB-INF/jsp/registration/hsp-medicalHistory.jsp
- app/src/main/webapp/WEB-INF/jsp/registration/hsp-registration.jsp
> JSPs for stuff

- app/src/main/java/org/teamone/client/healthconditions/HealthConditionsController.java
- app/src/main/java/org/teamone/client/medicalhistory/MedicalHistoryController.java
- app/src/main/java/org/teamone/client/patient/PersonalController.java
- app/src/main/java/org/teamone/client/patient/SelectPatientController.java
- app/src/main/java/org/teamone/client/registration/RegistrationController.java
- app/src/main/webapp/WEB-INF/jsp/patient/patient-PersonalInformation.jsp
Modified .java files to properly use user variable:
HealthConditionsController.java
MedicalHistoryController.java
PersonalController.java
RegistrationController.java
Modified SelectPatientController.java so buttons redirected to the correct page.
Modified patient-PersonalInformation.jsp so that it says "Update" rather than "Next" on its button
Added TODOs because I did not know how to add buttons to the patient display.
> Update to most of my controllers

- app/src/main/java/org/teamone/client/patient/PersonalController.java
- app/src/main/webapp/WEB-INF/jsp/patient/patient-PersonalInformation.jsp
> fixingGender-frontend

- app/src/main/java/org/teamone/client/prescription/PrescriptionController.java
- app/src/main/webapp/WEB-INF/jsp/prescription/createprescription.jsp
- app/src/main/webapp/WEB-INF/jsp/prescription/editprescription.jsp
- app/src/main/webapp/WEB-INF/jsp/prescription/printprescription.jsp
Printing for medications should be functioning
> printMedications-frontend

- app/src/main/webapp/WEB-INF/jsp/prescription/editprescription.jsp
made it so the colors are no longer animated
> made it so the colors are no longer animated

- app/src/main/java/org/teamone/client/appointments/AppointmentController.java
- app/src/main/java/org/teamone/client/appointments/AppointmentListController.java
- app/src/main/java/org/teamone/client/auth/LoginController.java
- app/src/main/java/org/teamone/client/healthconditions/HealthConditionsController.java
- app/src/main/java/org/teamone/client/lab/RequestLabTestController.java
- app/src/main/java/org/teamone/client/patient/PersonalController.java
- core/src/main/java/org/teamone/core/labs/LabReport.java
- core/src/main/java/org/teamone/core/labs/LabTestRequest.java
- core/src/main/java/org/teamone/core/users/HSP.java
- core/src/main/java/org/teamone/core/users/Patient.java
patient can now update health conditions through button. removed TODO
> patient can now update health conditions through button. removed TODO

- app/src/main/webapp/WEB-INF/jsp/appointment/createAppointment.jsp
- app/src/main/webapp/js/datepaginator.js
> fixed vulnerability

- app/src/main/java/org/teamone/client/registration/RegistrationController.java
- backup-cse360.sql
- core/src/test/java/org/teamone/core/AAPreloadRegisterTest.java
- core/src/test/java/org/teamone/core/AARegisterTest.java
> updated register

- app/src/main/webapp/WEB-INF/jsp/appointment/createAppointment.jsp
- app/src/main/webapp/WEB-INF/jsp/auth/user.jsp
- core/src/test/java/org/teamone/core/AppointmentTester.java
> Fix hsp format

- app/src/main/webapp/WEB-INF/jsp/alert/hsp.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/DoctorList.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/PatientList.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/PatientSchedAppt.jsp
- app/src/main/webapp/WEB-INF/jsp/appointment/createAppointmentHSP.jsp
- app/src/main/webapp/WEB-INF/jsp/prescription/editprescription.jsp
- app/src/main/webapp/WEB-INF/jsp/prescription/printprescription.jsp
- app/src/main/webapp/WEB-INF/tags/footer.jspf
- app/src/main/webapp/js/appointments.js
- app/src/main/webapp/js/datepaginator/datepaginator.js
fixed some css stuff. enforced spaces in appointment
> fixed some css stuff. enforced spaces in appointment

- app/src/main/webapp/WEB-INF/jsp/alert/alert.jsp
- app/src/main/webapp/WEB-INF/jsp/alert/hsp.jsp
- app/src/main/webapp/WEB-INF/jsp/patient/selectpatient.jsp
- app/src/main/webapp/WEB-INF/tags/navbar.jspf
- core/src/main/java/org/teamone/core/SQL/AlertSQL.java
updated alerts to be local SQL connections, no static
> updated alerts to be local SQL connections, no static

- app/src/main/java/org/teamone/client/patient/SelectPatientController.java
- app/src/main/webapp/WEB-INF/jsp/appointment/createAppointmentPatient.jsp
- core/src/main/java/org/teamone/core/SQL/AppointmentSQL.java
update doctor select patient list
> update doctor select patient list
